services:
  router1:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2,router3,router4,router5
    - my_ip=172.20.1.3
    - my_name=router1
    - router2_ip=172.20.2.3
    - router3_ip=172.20.3.3
    - router4_ip=172.20.4.3
    - router5_ip=172.20.5.3
    networks:
      subnet_1:
        ipv4_address: 172.20.1.3
      subnet_2:
        ipv4_address: 172.20.2.4
      subnet_3:
        ipv4_address: 172.20.3.4
      subnet_4:
        ipv4_address: 172.20.4.4
      subnet_5:
        ipv4_address: 172.20.5.4
    cap_add:
    - NET_ADMIN
  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1
    - my_ip=172.20.2.3
    - my_name=router2
    - router1_ip=172.20.1.3
    networks:
      subnet_2:
        ipv4_address: 172.20.2.3
      subnet_1:
        ipv4_address: 172.20.1.5
    cap_add:
    - NET_ADMIN
  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1
    - my_ip=172.20.3.3
    - my_name=router3
    - router1_ip=172.20.1.3
    networks:
      subnet_3:
        ipv4_address: 172.20.3.3
      subnet_1:
        ipv4_address: 172.20.1.6
    cap_add:
    - NET_ADMIN
  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1
    - my_ip=172.20.4.3
    - my_name=router4
    - router1_ip=172.20.1.3
    networks:
      subnet_4:
        ipv4_address: 172.20.4.3
      subnet_1:
        ipv4_address: 172.20.1.7
    cap_add:
    - NET_ADMIN
  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1
    - my_ip=172.20.5.3
    - my_name=router5
    - router1_ip=172.20.1.3
    networks:
      subnet_5:
        ipv4_address: 172.20.5.3
      subnet_1:
        ipv4_address: 172.20.1.8
    cap_add:
    - NET_ADMIN
  host1a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.100
    depends_on:
    - router1
    cap_add:
    - NET_ADMIN
  host1b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.110
    depends_on:
    - router1
    cap_add:
    - NET_ADMIN
  host2a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.100
    depends_on:
    - router2
    cap_add:
    - NET_ADMIN
  host2b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.110
    depends_on:
    - router2
    cap_add:
    - NET_ADMIN
  host3a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_3:
        ipv4_address: 172.20.3.100
    depends_on:
    - router3
    cap_add:
    - NET_ADMIN
  host3b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_3:
        ipv4_address: 172.20.3.110
    depends_on:
    - router3
    cap_add:
    - NET_ADMIN
  host4a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.100
    depends_on:
    - router4
    cap_add:
    - NET_ADMIN
  host4b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.110
    depends_on:
    - router4
    cap_add:
    - NET_ADMIN
  host5a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.100
    depends_on:
    - router5
    cap_add:
    - NET_ADMIN
  host5b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.110
    depends_on:
    - router5
    cap_add:
    - NET_ADMIN
networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
  subnet_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.4.0/24
  subnet_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.5.0/24
